/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DxVideo: typeof import('./src/components/DxVideo/DxVideo.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterBase: typeof import('./src/components/Footer/FooterBase.vue')['default']
    FooterHelp: typeof import('./src/components/Footer/FooterHelp.vue')['default']
    HeaderUser: typeof import('./src/components/Header/HeaderUser.vue')['default']
    IEpArrowLeft: typeof import('~icons/ep/arrow-left')['default']
    IEpCircleCheck: typeof import('~icons/ep/circle-check')['default']
    MenusIndex: typeof import('./src/components/Menus/MenusIndex.vue')['default']
    OrderPopup: typeof import('./src/components/orderPopup/orderPopup.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard/ProductCard.vue')['default']
    ProductCardSimple: typeof import('./src/components/ProductCard/ProductCardSimple.vue')['default']
    ProductFocusing: typeof import('./src/components/ProductFocusing/ProductFocusing.vue')['default']
    ProductListMode: typeof import('./src/components/ProductListMode/ProductListMode.vue')['default']
    ProductPopup: typeof import('./src/components/Popup/productPopup.vue')['default']
    ProductSkuPopup: typeof import('./src/components/Popup/productSkuPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableAddress: typeof import('./src/components/Table/TableAddress.vue')['default']
    TableOrder: typeof import('./src/components/Table/TableOrder.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
